### ISSUE TITLE
How can I run this pro with a pretrained model?

### ISSUE THREAD

**Issue by Wisgon** [bruceyang2012/face-detection-with-mobilenet-ssd#1]
Can you give me a tutorial about testing to get the test result you had shown.

**Comment by bruceyang2012** [comment]
you can find the code in face_train.ipynb.

**Comment by Wisgon** [comment]
Thanks to reply, I have a problem here.
When I excute :
model_path = './models/'
model_name = 'ssd_mobilenet_face_epoch_25_loss0.0916.h5'
model.load_weights(model_path + model_name,  by_name= True)

it raise an error:
**```

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-52562d2e12df> in <module>()
      2 model_name = 'ssd_mobilenet_face_epoch_25_loss0.0916.h5'
      3 
----> 4 model.load_weights(model_path + model_name,  by_name= True)
      5 
      6 print (colored('weights %s loaded' % (model_path + model_name), 'green'))

~/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/topology.py in load_weights(self, filepath, by_name)
   2614         if h5py is None:
   2615             raise ImportError('`load_weights` requires h5py.')
-> 2616         f = h5py.File(filepath, mode='r')
   2617         if 'layer_names' not in f.attrs and 'model_weights' in f:
   2618             f = f['model_weights']

~/anaconda3/envs/dl/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

~/anaconda3/envs/dl/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

```**

Is that because the model file has broken or I use a wrong version of h5py?
The version of h5py I using is 2.7.1 and I had tried 2.6.0, and same error raise.

**Comment by Wisgon** [comment]
I find the problem! The pro I download from "git clone" or  from "download zip", the file "ssd_mobilenet_face_epoch_25_loss0.0916.h5" is only 133byte, and I see the file on github is 15.7MB, so I download it  and now it can open the file  corectly.

**Comment by Wisgon** [comment]
I got a problem when I predicting my own image.
The code I got error is:


```
for i in range(1):
     X, y, filenames = cv2.imread('./test_data/song1.jpg'), [1], 'song1.jpg'

     y_pred = model.predict(X)
```


I use cv2.imread() to get the image's numpy array, and it's three dimensions, then I got:
Error when checking : expected input_1 to have 4 dimensions, but got array with shape (974, 800, 3)

So how can I load my own image to predict?

**Comment by Wisgon** [comment]
I change the code like this and solve the problem:

```
for i in range(1):
    img = image.load_img('./test_data/song1.jpg', target_size=(img_height, img_width))
    img = image.img_to_array(img)
    X, y, filenames = img[None], [1], 'song1.jpg'
    y_pred = model.predict(X)
```

**Comment by bruceyang2012** [comment]
you can use this code to expand the dimensions:
x = np.expand_dims(x, axis=0)

**Comment by Wisgon** [comment]
Thanks you very much for reply, I can run my own picture now.

**Comment by exnx** [comment]
Hi @Wisgon, were you able to use the pretrained model with a cpu?  Or did you use GPU?  If CPU, was it really slow?
