### ISSUE TITLE
bad bbox classification results

### ISSUE THREAD

**Issue by RodinIvan** [bruceyang2012/face-detection-with-mobilenet-ssd#11]
Hi @bruceyang2012 !

I'm trying to solve hand detection problem (2 classes: 'background' and 'hand') on custom dataset using your model. I've adjusted data to the desired format, so there is no problem with data loading.

However, after training I get the first 2 coordinates in ```y_pred```  [0.5, 0.5] in most of the cases, and [0.5+eps, 0.5-eps] in the rest minority, which means that model cannot classify bounding boxes and doesn't recognize "active" class (hand) at all.

I've tried to play with different parameters of ```SSDLoss()```, like setting ```beta=2.0``` and changing ```neg_pos_ratio``` and ```neg_min``` but it didn't change the picture.
Can you please give any suggestions on what to do next and what should I change to get reasonable classification results?

Thanks!

**Comment by bruceyang2012** [comment]
Hi @RodinIvan , it looks like your model is not converging, and you can try to adjust the learning rate.
