### ISSUE TITLE
There is an error in class AnchorBoxes.

### ISSUE THREAD

**Issue by lipanpeng** [bruceyang2012/face-detection-with-mobilenet-ssd#12]
In keras_layer_AnchorBoxes.py, there is an error in call() in class AnchorBoxes. 
boxes_tensor[:, :, :, 2] = wh_list[:, 0] # Set w
boxes_tensor[:, :, :, 3] = wh_list[:, 1] # Set h
could not broadcast input array from shape (2) into shape (w, h, num_boxes)

**Comment by bruceyang2012** [comment]
Maybe your data format is wrong, try to show the boxes on the images
