### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by mosheliv** [bruceyang2012/face-detection-with-mobilenet-ssd#3]
Hi,
Just wondering why you chose not to include any augmentations in the train_dataset.generate? For example, translation would enable the faces of the people on the ground in the second photo to be detected. I am going to implement something similar and was wondering if you had any rational behind not augmenting. Was it the training time?

Regards,
Moshe

**Comment by bruceyang2012** [comment]
Hi, @mosheliv, sorry to reply so late. In fact, i have done it in face_train.ipynb. In the train_dataset.generate, it's closed by default, but you can open it when training.
