### ISSUE TITLE
I find one error in your code

### ISSUE THREAD

**Issue by zcc720** [bruceyang2012/face-detection-with-mobilenet-ssd#4]
wider_extract.py

 if isValid=='0' and (isOccluded!='2') and (isBlur!='2'):
                    bb.append(bb_each)

**Comment by zcc720** [comment]
In the period of prepare data：
Download WIDER Face from Official Website , and put it into face_data folder in face_generator.py.
I do not quite understand this point. Is the face_folder folder mean the folder name dataset?
then how to use them?

**Comment by sri-teja** [comment]
@zcc720 You can download the WIDER Face Train and Val datasets from the official website and put them in `dataset` folder given this repository. The face_generator.py looks for images in the `dataset` folder according to the `img_path` variable in `line 471` while generating batches.

**Comment by buaa-luzhi** [comment]
@zcc720 
wider_extract.py
if int(isValid)==0 and int(isOccluded)!=2 and int(isBlur)!=2):
     bb.append(bb_each)
I think that's ok.

**Comment by buaa-luzhi** [comment]
@zcc720 @sri-teja 
Hello,  in wider_extract.py,  there is another problem.
bb_ref_cnt  always grater than 0, so  
if bb_ref_cnt == 0 
   face_bb[f_name]  = bb
face_bb is always empty. So wider_test.npy is also empty.
Thank you !

**Comment by buaa-luzhi** [comment]
@zcc720 @sri-teja 
Last question, 
How do you generate the 'wider_face_train_bbx_gt.txt' file, thanks very much!

**Comment by bruceyang2012** [comment]
@buaa-luzhi you can download the wider_face_train_bbx_gt.txt form WIDER Face Official Website.
