### ISSUE TITLE
widerface training 

### ISSUE THREAD

**Issue by omrylcn** [bruceyang2012/face-detection-with-mobilenet-ssd#5]
Hi yang shuang , thanks for sharing  repo, it is really great work. if you let me , I will get  a problem is sharing  with you . When I  trained wider face data by your face_train.ipynb , I got high val error . Also my epoch is 30 . I got min error 0.10801 .I dont understand why it happen. What can you  say  doing preprocessing  for data , What is your plan to trian data

**Comment by zcc720** [comment]
Do you know why it detects so slowly?

**Comment by omrylcn** [comment]
hi , how much slowly , what is fps , what do use cpu and gpu , also keras  is slower than  like tensorflow and pytorch
