### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by momo1986** [bruceyang2012/face-detection-with-mobilenet-ssd#6]
Hello,
thanks for sharing.
I have two questions:
1. I can do some training to reduce the val_loss under 0.5, however, when I test on single images, the result is wierd. Thus, is there a demo, how can I load the model and test it on single image, is it needed to transform it to the batch-format data?
2. Second, if I do some my own training task, like hand detection task, will the transfer learning with coco or pascal-pretrained model be good?
Thanks & Regards!

**Comment by buaa-luzhi** [comment]
@momo1986 
Hello, 

train_dataset = BatchGenerator(images_path=train_data, 
                                                   image_set_path=data_path,
                                                   include_classes='all', 
                                                   box_output_format = ['class_id', 'xmin', 'xmax', 'ymin', 'ymax'])

‘’image_set_path‘’  is not used in the 'BatchGengrator'.  How do you solve it.
Thank you!

**Comment by buaa-luzhi** [comment]
@momo1986 
The results are not very good, especially for small targets。

**Comment by hongrui16** [comment]
Hello, have you ever trained the model and tested it successfully. I tried to train the model on Pascalvoc2012 , and it almost could not work. I did training on coco, it didn’t converge. So I decided to check the model in using the same group of images as train and test dataset. The map should be 1, but the actual result is closed to 0. 

So I wonder whether there is an error in the code.
I have checked the code many times, and please help me.

**Comment by xiaodanWang** [comment]
@momo1986 
Hello,

train_dataset = BatchGenerator(images_path=train_data,
image_set_path=data_path,
include_classes='all',
box_output_format = ['class_id', 'xmin', 'xmax', 'ymin', 'ymax'])
‘’image_set_path‘’ is not used in the 'BatchGengrator'. 
How do you solve it.
Thank you!

**Comment by bruceyang2012** [comment]
@xiaodanWang The bug has been fixed.
